version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests

  deploy_to_render:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger Render Deploy
          command: |
            curl -X POST "$RENDER_DEPLOY_HOOK"

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy_to_render:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main